### ISSUE TITLE
Hot to convert []byte to float?

### ISSUE THREAD

**Issue by IAkumaI** [blugelabs/bluge#102]
As I understand, the one way to get document field values is `VisitStoredFields`. Callback retrive value as []byte.
So, text fields is simply converted via `string(value)`.
But how to convert Numeric (float64) fields?

I tried
```
func Float64frombytes(bytes []byte) float64 {
	bits := binary.BigEndian.Uint32(bytes)
	float := math.Float32frombits(bits)
	return float64(float)
}
```
and
```
func Float64frombytes(bytes []byte) float64 {
	bits := binary.BigEndian.Uint64(bytes)
	float := math.Float64frombits(bits)
	return float
}
```
But both of them does not works correct.
I tried LittleEndian - still no result.

**Comment by IAkumaI** [comment]
I don't know why, but when I "just try to found solution" - it does not work.
But if I write issue - I'll found solution in 5 second.

There is function `bluge.DecodeNumericFloat64(value []byte) (float64, error)` which can decode value to float64.
May be you can add this to docs?

**Comment by mschoch** [comment]
In the future I'll wait a few minutes before spending time on it.

Yes this is the correct answer to your question.

**Comment by IAkumaI** [comment]
Sorry :)

But I think this issue will help someone in future.
