### ISSUE TITLE
Date aggregations support

### ISSUE THREAD

**Issue by jney** [blugelabs/bluge#125]
Hi. I am pretty new there. Not sure it's the best place to ask question. If it's not just tell me and I'll use the appropriate channel.

I want to filter by date some results (kind of facets). I tried `AddShould` and `AddMust` but it wasn't the appropriate concept.
So after reading a while I tried aggregations, as it seems to be the mechanism to filter search.

Here's a simplified version of my code:

```go
func Search(s Input) (Results, error) {
	q := bluge.NewBooleanQuery().AddShould(bluge.NewMatchQuery(s.Query).SetField(DESCRIPTION))
	req := bluge.NewTopNSearch(100, q)
	if !s.Start.IsZero() || !s.End.IsZero() {
		dateAgg := aggregations.DateRanges(search.Field(DATE))
		dateAgg.AddRange(aggregations.NewDateRange(s.Start, s.End))
		req.AddAggregation(DATE, dateAgg)
	}
	reader, _ := openReader()
	dmi, _ := reader.Search(context.Background(), req)
	res := make(Results, 0)
	next, err := dmi.Next()
	for err == nil && next != nil {
		next.VisitStoredFields(func(k string, v []byte) bool {
			fmt.Println("k:", k) // `k` will only be `_id` but we stored other stuff...
			if k == "_id" {
				res = append(res, Result{ID: string(v), Score: next.Score})
			}
			return true
		})
		next, err = dmi.Next()
	}
	return res, reader.Close()
}
```

But aggregation seems to have no effect.
I guess I should mention I read the doc and the beer-search example, but I probably missed something.
Thanks

**Comment by mschoch** [comment]
Welcome @jney 

Aggregations are not used to filter results, they are used to describe the result set (even search hits not returned).  For example, lets say you do a simple search for the term "foo".  It might match 578 documents, but by default we're only going to return the top 10.  Aggregations allow you collect and return some useful details about all 578.  For example, if we had used a date aggregation, it could have told us that 100 of the 578 were recently updated.  Think of it as a way to return aggregated details about the entire set of matching documents.

That said, it sounds like you're interested in filtering your search results by date, and for that you do not use aggregations, you will use the DateRangeQuery.  There is a more complete example of indexing and searching dates here:  https://github.com/blugelabs/bluge_examples/blob/master/dates/main.go

Please start by taking a look at this, and see if that answers your questions, or if you have more questions.

**Comment by jney** [comment]
thank you pointing me this out
I had to have a `BooleanQuery` of `BooleanQuery` plus `DateRange` to apply date filtering on my subset
this lib so great to work with
