### ISSUE TITLE
TestBug87 fails in custom implementation of search.Context

### ISSUE THREAD

**Issue by danvixent** [blugelabs/bluge#126]
TestBug87 constantly fails with 

```go
expected id '0' to match sort value ''
```
in our custom `search.Context`, we needed the `DocumentMatchPool` to allow concurrent `Get` & `Put` see [here](https://github.com/zinclabs/bluge/pull/1), however, switching to our custom implementation causes TestBug87 to always fail.

I have been looking into the code to try and get a fix, any pointers for me while i keep doing that?

**Comment by mschoch** [comment]
This test runs a query which specifies a sort order of `_id`.

The error message you've shown indicates that the returned item has an incorrect sort value.  That sort value is not just incorrect it is also empty.

I have no idea about the changes you've made, but I would start by investigating why the item return lacked a sort value that was expected.

**Comment by danvixent** [comment]
Thank you, i think i have found the issue 😅
