### ISSUE TITLE
Question on aggregation bucket

### ISSUE THREAD

**Issue by danvixent** [blugelabs/bluge#127]
I am curious as to why a document is being consumed in the aggregation bucket, when it could potentially be dropped as seen in the `TopNCollect.collectSingle` method:

```go
if len(hc.neededFields) > 0 {
		err = d.LoadDocumentValues(ctx, hc.neededFields)
		if err != nil {
			return err
		}
	}

	// compute this hits sort value
	hc.sort.Compute(d)

	// calculate aggregations
	bucket.Consume(d)

	// support search after based pagination,
	// if this hit is <= the search after sort key
	// we should skip it
	if hc.searchAfter != nil {
		// exact sort order matches use hit number to break tie
		// but we want to allow for exact match, so we pretend
		hc.searchAfter.HitNumber = d.HitNumber
		if hc.sort.Compare(d, hc.searchAfter) <= 0 {
			return nil
		}
	}

	// optimization, we track lowest sorting hit already removed from heap
	// with this one comparison, we can avoid all heap operations if
	// this hit would have been added and then immediately removed
	if hc.lowestMatchOutsideResults != nil {
		cmp := hc.sort.Compare(d, hc.lowestMatchOutsideResults)
		if cmp >= 0 {
			// this hit can't possibly be in the result set, so avoid heap ops
			ctx.DocumentMatchPool.Put(d)
			return nil
		}
	}

	removed := hc.store.AddNotExceedingSize(d, hc.size+hc.skip)
```

As seen, the document may not make it to the store even after consuming it in the aggregation bucket. Any explainers are appreciated! Thank you.

**Comment by mschoch** [comment]
Yes, that is the intended design of aggregations.  All of the documents seen at this point of execution have matched the query, so they are all processed by the aggregations.  However, depending on the sort key, and how many results you requested, the document may not be a part of the result set returned to the user.

Consider an example where you have 1000 documents.  You search for the top 10 documents containing "foo", and your result set will contain the 10 highest ranking documents.  However, aggregations can provide you additional information about the other documents that matched, even the ones that weren't returned to you.  For example:
- how many total documents matched (100)
- how many of the 100 were updated recently (using date range aggregation)
- of the 100 matching documents, which tags were most popular (using term bucket aggregation)

So, the aggregations let us do additional processing on all the matching documents, not just the subset of matches returned to the user.

**Comment by danvixent** [comment]
This is all i needed to know, thank you very much @mschoch.
