### ISSUE TITLE
Install fails due to willf/bitset

### ISSUE THREAD

**Issue by tmm1** [blugelabs/bluge#64]
```
$ go get -u github.com/blugelabs/bluge
go get: github.com/willf/bitset@v1.1.10 updating to
	github.com/willf/bitset@v1.2.0: parsing go.mod:
	module declares its path as: github.com/bits-and-blooms/bitset
	        but was required as: github.com/willf/bitset
```

**Comment by mschoch** [comment]
Thanks, yes we just fixed this mess in bleve, it will need to be done here too.

**Comment by mschoch** [comment]
@tmm1 I still get this error with this command,  I though it was just Googles module proxy cache, but I can't figure it out.

**Comment by tmm1** [comment]
It works without -u

I don't understand why.

**Comment by mschoch** [comment]
Likewise, I am not sure.

**Comment by mschoch** [comment]
Oh wait, it's because of the of the other repos still needs to be updated :(

**Comment by mschoch** [comment]
Reopening as a reminder to myself

**Comment by mschoch** [comment]
@tmm1 I think this is fixed now, please confirm when you get a chance.  Thanks.
