### ISSUE TITLE
Question: is it possible to add additonal values like recency to the score?

### ISSUE THREAD

**Issue by enex** [blugelabs/bluge#94]
I would like to configure how search results are scored based on other additional parameters that are not direct matches. For example I would want the recency of a document to be weighted into the score so they appear in front of other documents that may satisfy the query but are older and thus not that relevant. Is that possible or even the right thing to do to achieve the intended result?

Another usecase is if i have a like to dislike ratio and i would like the ratio to effect the score/ranking but also maintain searchability

I hope this is the right place to ask, wasn't sure

**Comment by enex** [comment]
I just realized that I could use a custom sort to achieve that, is that right?

**Comment by mschoch** [comment]
Welcome,

Yes, it is possible to have custom logic that influences the score of a document at query time.  There are several related interfaces, and you can accomplish the same thing several different ways.  You might see interfaces for Similarity and Scorer, and while these do relate to scoring, they currently cannot be used for the type of scoring you're asking about.

Instead, one approach is to build a custom Query which wraps the actual query you want to run.  Internally all the "query" logic is just a pass-though to the original query, but it gives us an opportunity to alter the score before the search hit is returned.

You can see a full example of this approach here: https://github.com/mschoch/bluge-custom-score

The example in that repo actualy goes a step further and loads values from the search hit document, and can use those values in the custom scoring as well.  This would be how I would incorporate a like/dislike ratio.  Basically imagine you have a nightly analytics job that computes the like/dislike popularity rating, and stores it back into the original document.  Then here, your custom query implementation can load that popularity value and use it.

I hope this helps, if you have more follow-up questions let us know.

**Comment by mschoch** [comment]
I realize I didn't mention recency specifically.  If each document stored a field for create/update timestamp, you can load that at query time and compute the document's age, and the factor it into the scoring.

Also, for recency you can also use a more coarse-grained approach.  Simply use matching date ranges to compute apply a boost to the score.  So, at query time, compute windows for say, last week, last month, last year, etc.  Add optional query clauses which match these ranges and use diminishing boost values.  This is more coarse-grained, but also a bit lighter-weight.

**Comment by enex** [comment]
Thank you, that is really helpful.
